# application.yml
server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://sujan:sujan123@cluster0.g3u2o59.mongodb.net/taxi_booking?retryWrites=true&w=majority&appName=Cluster0}
  main:
    allow-bean-definition-overriding: true

# JWT Configuration
jwt:
  # Base64 encoded secret key (min 256 bits)
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLWZvci10YXhpLWJvb2tpbmctcGxhdGZvcm0=}
  expiration: ${JWT_EXPIRATION:86400000} # 24 Hours in milliseconds

# Razorpay Credentials
razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:rzp_test_mockKeyId123}
    secret: ${RAZORPAY_KEY_SECRET:mockKeySecret456}

# Owner/Driver Details
driver:
  phone: ${DRIVER_PHONE:918670175981}
